#!/usr/bin/env bash
# Bumps bungkus-mc's version everywhere it is written, for the release PR.
#
#   scripts/bump-version.sh           next version: 0.1.0-beta.3 -> 0.1.0-beta.4,
#                                     0.1.0 -> 0.1.1
#   scripts/bump-version.sh 0.2.0     exactly this version
#
# Changes Cargo.toml, the README status line, Cargo.lock and the version in
# the header of every rendering golden (regenerated by the tests), then
# runs the tests again without regenerating. Commits nothing.
set -euo pipefail

cd "$(dirname "$0")/.."

current="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)"
[ -n "$current" ] || { echo "no version in Cargo.toml" >&2; exit 1; }

if [ $# -ge 1 ]; then
  next="${1#v}"
elif [[ "$current" =~ ^(.*[.-])([0-9]+)$ ]]; then
  # The last number: the pre-release counter, or the patch of a stable one.
  next="${BASH_REMATCH[1]}$((BASH_REMATCH[2] + 1))"
else
  echo "cannot tell what follows $current; pass the version" >&2
  exit 1
fi

if ! [[ "$next" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ ]]; then
  echo "$next is not a version (want 1.2.3 or 1.2.3-beta.4)" >&2
  exit 1
fi
if [ "$next" = "$current" ]; then
  echo "already at $current" >&2
  exit 1
fi
if git rev-parse -q --verify "refs/tags/v$next" >/dev/null; then
  echo "v$next is already released" >&2
  exit 1
fi

# perl, not sed -i: the same command on macOS and Linux.
CUR="$current" NEXT="$next" perl -pi -e \
  's/^version = "\Q$ENV{CUR}\E"/version = "$ENV{NEXT}"/ if !$done && /^version = / and $done = 1' \
  Cargo.toml
CUR="$current" NEXT="$next" perl -pi -e 's/\(`\Q$ENV{CUR}\E`\)/(`$ENV{NEXT}`)/' README.md

# The goldens carry the version; this also rewrites Cargo.lock.
UPDATE_GOLDEN=1 cargo test --all-features --quiet >/dev/null
cargo test --all-features --quiet >/dev/null

echo "$current -> $next"
